version: '3.8'

services:
  
  server:
    image: go-server # docker-compose up will use locally built image if found
    build: ./server # if not found, it'll be built
    expose: 
      - 80
    volumes: 
      - ./server:/go/src/app

  proxy:
    build: ./proxy
    ports: 
      - 8001:80
    volumes: 
      - ./proxy:/go/src/app